"""Regenerate bd_foods.json from bd_foods_master.csv.

The CSV is the source of truth: you (and the nutritionist) edit it,
this script produces what the app loads. Validation runs first, and
nothing is written if any check fails.

Usage:  python csv_to_json.py
"""
import csv
import json
import sys
from pathlib import Path

SRC = Path(__file__).parent / "bd_foods_master.csv"
OUT = Path(__file__).parent / "bd_foods.json"

SOURCE_META = {
    "name": "Food Composition Table for Bangladesh",
    "publisher": "Institute of Nutrition and Food Science, University of Dhaka",
    "support": "NFPCSP, Ministry of Food (GoB), FAO, USAID, EU",
    "edition": "First Edition, June 2013",
    "isbn": "978984337522-3",
    "url": "https://www.fao.org/fileadmin/templates/food_composition/documents/FCT_10_2_14_final_version.pdf",
}

NOTES = {
    "values_basis": "All per_100g values are copied from the FCT, edible portion, fresh weight.",
    "portion_basis": "portion_grams is OUR assumption for a typical household serving. It is NOT from the FCT.",
    "cooked_values": "The FCT derives cooked-food values using yield and retention factors rather than analysing each cooked dish. Noted as a limitation.",
    "preparation": "Boiled entries are without salt or oil. Real home cooking adds both.",
    "glycemic_class": "Assigned by us from carbohydrate content and common dietary guidance; NOT measured GI values from the FCT.",
    "coverage": "Groups 01-05 (cereals, pulses, vegetables, leafy vegetables, starchy roots) transcribed. Groups 06-15 (nuts, spices, fruits, fish, meat, eggs, milk, oils, beverages) NOT yet transcribed - queries about them are correctly refused.",
    "pipeline": "bd_foods_master.csv is the source of truth; this file is generated by csv_to_json.py.",
}

VALID_GI = {"high", "medium", "low", ""}
VALID_FLAGS = {"diabetes_caution", "kidney_caution", "hypertension_caution"}


def num(value, field, row_id, errors, integer=False):
    """Parse a numeric cell, recording an error instead of raising."""
    text = (value or "").strip()
    if not text:
        return None
    try:
        return int(float(text)) if integer else float(text)
    except ValueError:
        errors.append(f"{row_id}: {field} is not a number ({text!r})")
        return None


def validate(foods):
    """Checks that must all pass before the JSON is written."""
    errors, warnings = [], []

    seen_ids, seen_codes = set(), set()
    for f in foods:
        fid = f["id"]

        if fid in seen_ids:
            errors.append(f"{fid}: duplicate id")
        seen_ids.add(fid)

        if f["fct_code"] in seen_codes:
            warnings.append(f"{fid}: fct_code {f['fct_code']} used more than once")
        seen_codes.add(f["fct_code"])

        p = f["per_100g"]
        if p["calories"] is None:
            errors.append(f"{fid}: missing calories")
            continue

        # Atwater cross-check: recompute energy from macros using the FCT's
        # own conversion factors. A large gap means a transcription slip.
        est = (4 * (p["protein_g"] or 0) + 9 * (p["fat_g"] or 0)
               + 4 * (p["carbs_g"] or 0) + 2 * (p["fiber_g"] or 0))
        if p["calories"] > 0 and abs(est - p["calories"]) / p["calories"] > 0.25:
            warnings.append(
                f"{fid}: energy {p['calories']} vs macros {est:.0f} — check transcription")

        # macros cannot exceed 100 g per 100 g
        total = sum((p[k] or 0) for k in ("protein_g", "fat_g", "carbs_g", "fiber_g"))
        if total > 100:
            errors.append(f"{fid}: macros total {total:.1f}g per 100g")

        if f.get("glycemic_class") not in VALID_GI:
            errors.append(f"{fid}: bad glycemic_class {f.get('glycemic_class')!r}")

        for flag in f.get("condition_flags", []):
            if flag not in VALID_FLAGS:
                errors.append(f"{fid}: unknown condition flag {flag!r}")

        if not f.get("portion_grams"):
            warnings.append(f"{fid}: no portion_grams — per-portion values unavailable")

        if not f.get("name_banglish"):
            warnings.append(f"{fid}: no Banglish aliases — users typing romanised will miss it")

    return errors, warnings


def main():
    if not SRC.exists():
        sys.exit(f"{SRC.name} not found. Run json_to_csv.py first.")

    foods = []
    errors = []

    with open(SRC, encoding="utf-8-sig") as f:
        for row in csv.DictReader(f):
            fid = (row.get("id") or "").strip()
            if not fid:
                continue                       # skip blank lines

            foods.append({
                "id": fid,
                "fct_code": (row.get("fct_code") or "").strip(),
                "name_en": (row.get("name_en") or "").strip(),
                "name_bn": (row.get("name_bn") or "").strip(),
                "name_banglish": [a.strip() for a in (row.get("name_banglish") or "").split("|") if a.strip()],
                "category": (row.get("category") or "").strip(),
                "per_100g": {
                    "calories": num(row.get("calories_100g"), "calories", fid, errors, integer=True),
                    "protein_g": num(row.get("protein_g_100g"), "protein", fid, errors),
                    "fat_g": num(row.get("fat_g_100g"), "fat", fid, errors),
                    "carbs_g": num(row.get("carbs_g_100g"), "carbs", fid, errors),
                    "fiber_g": num(row.get("fiber_g_100g"), "fiber", fid, errors),
                },
                "portion_local": (row.get("portion_local") or "").strip(),
                "portion_grams": num(row.get("portion_grams"), "portion_grams", fid, errors, integer=True),
                "portion_basis": "assumed household serving",
                "glycemic_class": (row.get("glycemic_class") or "").strip() or None,
                "condition_flags": [c.strip() for c in (row.get("condition_flags") or "").split("|") if c.strip()],
                "verified": (row.get("verified") or "").strip().lower() in ("yes", "true", "1"),
                # carried through so the approval lives in the data
                "review_comment": (row.get("review_comment") or "").strip() or None,
            })

    val_errors, warnings = validate(foods)
    errors.extend(val_errors)

    for w in warnings:
        print(f"WARN  {w}")

    if errors:
        for e in errors:
            print(f"ERROR {e}")
        sys.exit(f"\n{len(errors)} error(s) — nothing written.")

    doc = {
        "schema_version": 2,
        "source": SOURCE_META,
        "notes": NOTES,
        "foods": foods,
    }
    with open(OUT, "w", encoding="utf-8") as f:
        json.dump(doc, f, ensure_ascii=False, indent=2)

    verified = sum(1 for f in foods if f["verified"])
    print(f"\nOK: wrote {len(foods)} foods ({verified} verified), {len(warnings)} warning(s).")


if __name__ == "__main__":
    main()